/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.dms.assign.gui;

import nz.ac.aut.dms.assign.model.ChatClient;

/**
 *
 * @author Dong Huang
 */
public class ChatGUI extends javax.swing.JFrame {

    /**
     * Creates new form ChatGUI
     */
    public ChatGUI(ChatClient chatClient) {
        this.chatClient = chatClient;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConnection = new javax.swing.JPanel();
        jTextFieldServerIP = new javax.swing.JTextField();
        jTextFieldServerPort = new javax.swing.JTextField();
        jTextFieldYourName = new javax.swing.JTextField();
        jLabelServerIP = new javax.swing.JLabel();
        jLabelServerPort = new javax.swing.JLabel();
        jLabelYourName = new javax.swing.JLabel();
        jButtonConnect = new javax.swing.JButton();
        jButtonDisconnect = new javax.swing.JButton();
        jPanelFriendList = new javax.swing.JPanel();
        jScrollPaneFriendList = new javax.swing.JScrollPane();
        jListFriendList = new javax.swing.JList<>();
        jPanelChatHistory = new javax.swing.JPanel();
        jScrollPaneChatHistory = new javax.swing.JScrollPane();
        jTextAreaChatHistory = new javax.swing.JTextArea();
        jPanelMessageInput = new javax.swing.JPanel();
        jButtonSend = new javax.swing.JButton();
        jCheckBoxBroadcast = new javax.swing.JCheckBox();
        jScrollPaneMessageInput = new javax.swing.JScrollPane();
        jTextAreaMessageInput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ChatClient");
        setResizable(false);

        jPanelConnection.setBorder(javax.swing.BorderFactory.createTitledBorder("Connection"));

        jTextFieldServerPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldServerPortActionPerformed(evt);
            }
        });

        jLabelServerIP.setText("Server IP:");

        jLabelServerPort.setText("Server Port:");

        jLabelYourName.setText("Your Name:");

        jButtonConnect.setText("Connect");

        jButtonDisconnect.setText("Disconnect");
        jButtonDisconnect.setActionCommand("");
        jButtonDisconnect.setEnabled(false);

        javax.swing.GroupLayout jPanelConnectionLayout = new javax.swing.GroupLayout(jPanelConnection);
        jPanelConnection.setLayout(jPanelConnectionLayout);
        jPanelConnectionLayout.setHorizontalGroup(
            jPanelConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConnectionLayout.createSequentialGroup()
                .addGroup(jPanelConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelServerIP, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelServerPort, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelYourName, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldServerIP)
                    .addComponent(jTextFieldServerPort)
                    .addComponent(jTextFieldYourName)))
            .addGroup(jPanelConnectionLayout.createSequentialGroup()
                .addComponent(jButtonConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDisconnect)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelConnectionLayout.setVerticalGroup(
            jPanelConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConnectionLayout.createSequentialGroup()
                .addGroup(jPanelConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldServerIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelServerIP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelServerPort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldYourName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelYourName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelConnectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConnect)
                    .addComponent(jButtonDisconnect)))
        );

        jPanelFriendList.setBorder(javax.swing.BorderFactory.createTitledBorder("Friend List"));

        jListFriendList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPaneFriendList.setViewportView(jListFriendList);

        javax.swing.GroupLayout jPanelFriendListLayout = new javax.swing.GroupLayout(jPanelFriendList);
        jPanelFriendList.setLayout(jPanelFriendListLayout);
        jPanelFriendListLayout.setHorizontalGroup(
            jPanelFriendListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneFriendList)
        );
        jPanelFriendListLayout.setVerticalGroup(
            jPanelFriendListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneFriendList, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanelChatHistory.setBorder(javax.swing.BorderFactory.createTitledBorder("Chat History"));

        jTextAreaChatHistory.setEditable(false);
        jTextAreaChatHistory.setColumns(20);
        jTextAreaChatHistory.setRows(5);
        jScrollPaneChatHistory.setViewportView(jTextAreaChatHistory);

        javax.swing.GroupLayout jPanelChatHistoryLayout = new javax.swing.GroupLayout(jPanelChatHistory);
        jPanelChatHistory.setLayout(jPanelChatHistoryLayout);
        jPanelChatHistoryLayout.setHorizontalGroup(
            jPanelChatHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneChatHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
        );
        jPanelChatHistoryLayout.setVerticalGroup(
            jPanelChatHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneChatHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanelMessageInput.setBorder(javax.swing.BorderFactory.createTitledBorder("Message Input"));

        jButtonSend.setText("Send");

        jCheckBoxBroadcast.setText("Broadcast");

        jTextAreaMessageInput.setColumns(20);
        jTextAreaMessageInput.setRows(5);
        jScrollPaneMessageInput.setViewportView(jTextAreaMessageInput);

        javax.swing.GroupLayout jPanelMessageInputLayout = new javax.swing.GroupLayout(jPanelMessageInput);
        jPanelMessageInput.setLayout(jPanelMessageInputLayout);
        jPanelMessageInputLayout.setHorizontalGroup(
            jPanelMessageInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMessageInputLayout.createSequentialGroup()
                .addComponent(jCheckBoxBroadcast)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSend))
            .addComponent(jScrollPaneMessageInput)
        );
        jPanelMessageInputLayout.setVerticalGroup(
            jPanelMessageInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMessageInputLayout.createSequentialGroup()
                .addComponent(jScrollPaneMessageInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMessageInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSend)
                    .addComponent(jCheckBoxBroadcast)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelConnection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelFriendList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelChatHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelMessageInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelConnection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFriendList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelChatHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelMessageInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldServerPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldServerPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldServerPortActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ChatGUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonDisconnect;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JCheckBox jCheckBoxBroadcast;
    private javax.swing.JLabel jLabelServerIP;
    private javax.swing.JLabel jLabelServerPort;
    private javax.swing.JLabel jLabelYourName;
    private javax.swing.JList<String> jListFriendList;
    private javax.swing.JPanel jPanelChatHistory;
    private javax.swing.JPanel jPanelConnection;
    private javax.swing.JPanel jPanelFriendList;
    private javax.swing.JPanel jPanelMessageInput;
    private javax.swing.JScrollPane jScrollPaneChatHistory;
    private javax.swing.JScrollPane jScrollPaneFriendList;
    private javax.swing.JScrollPane jScrollPaneMessageInput;
    private javax.swing.JTextArea jTextAreaChatHistory;
    private javax.swing.JTextArea jTextAreaMessageInput;
    private javax.swing.JTextField jTextFieldServerIP;
    private javax.swing.JTextField jTextFieldServerPort;
    private javax.swing.JTextField jTextFieldYourName;
    // End of variables declaration//GEN-END:variables

    private ChatClient chatClient = null;
}
